# Generated by Django 3.0.3 on 2020-02-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TempHum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse.Sensor')),
            ],
            options={
                'verbose_name': 'Temperature Humidity Reading',
                'verbose_name_plural': 'Temperature Humidity Readings',
            },
        ),
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(max_length=32)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='SensorTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse.Sensor')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse.Topic')),
            ],
            options={
                'verbose_name': 'Sensor Topic',
                'verbose_name_plural': 'Sensor Topics',
            },
        ),
    ]
