# Generated by Django 3.0.3 on 2020-02-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0003_temphum_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temphum',
            old_name='temp',
            new_name='temperature',
        ),
    ]
